Add extra checks

diff --git a/src/common_functions b/src/common_functions
--- a/src/common_functions
+++ b/src/common_functions
@@ -50,6 +50,10 @@ get_last_tag()
 {
 if [ $(git tag | wc -l) -gt 0 ]; then
    latestTag=`git describe --abbrev=0 --tags`
+   if [ $? -ne 0 ]; then
+     latestTag=0.1
+     echo "Could not extract the latest tag, will set it to 0.1"
+   fi
 else
    latestTag=0.1
 fi
